config/routes.rb
AKonRails::Application.routes.draw do
  root "static_pages#index"  
  
  get "index", to: "static_pages#index", as: "index"
  
  get "about/me", to: "static_pages#about/me", as: "aboutme"
  get "about/resume", to: "static_pages#about/resume", as: "resume"
  get "about/awards", to: "static_pages#about/awards", as: "awards"
  
  get "portfolio/sound", to: "static_pages#portfolio/sound", as: "sound"
  get "portfolio/design", to: "static_pages#portfolio/design", as: "design"
  get "portfolio/software", to: "static_pages#portfolio/software", as: "software"
  
  scope "/portfolio" do
    resources :works
  end

  

end

app/models/work.rb
class Work < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_var
  
  private
  
  def set_var
    @works = Work.all
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
    def aboutme
    end
    
    def resume
    end
    
    def awards
    end
  end

  def work
    def sound
    end
    
    def design
    end
    
    def software
    end
  end

  def contact
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    if @work.save
      redirect_to @work, notice: 'Work was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    if @work.update(work_params)
      redirect_to @work, notice: 'Work was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    redirect_to works_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:name, :series, :av, :category, :publisher, :role, :embed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="mainnav" id="bottomnav">
		<ul>
			<li class="about">
				<ul>
					<li class="aboutme"><%= link_to "About Me", aboutme_path %></li>
					<li class="resume"><%= link_to "Resume", resume_path %></li>
					<li class="awards"><%= link_to "Awards", awards_path %></li>
				</ul>
			</li>
			 /// 
			<li class="work">
				<ul>
					<li class="films"><%= link_to "Sound", sound_path %></li>
					<li class="design"><%= link_to "Design", design_path %></li>
					<li class="software"><%= link_to "Software", software_path %></li>
				</ul>
			</li>
			 /// 
			<li class="contact">
				<ul>
					<li><%= link_to "Twitter", "http://www.twitter.com/KodaSound" %></li>
					<li><%= link_to "Tumblr", "http://kodasound.tumblr.com "%></li>
					<li><%= link_to "LinkedIn", "http://www.linkedin.com/in/alankoda/" %></li>
					<li><%= link_to "Facebook", "http://www.facebook.com/pages/KodaSound/133981336687315"%></li>
				</ul>
			</li>
		</ul>
	</nav>

	<div id="credits">
		<p>site design by Alan Koda &copy;2012</p>
		<p><%= link_to "alan@alankoda.com", "mailto:alan@alankoda.com" %> • 
		<%= link_to "817.308.5446", "tel:+18173085446" %></p>
	</div>

</footer>

app/views/layouts/_head.html.erb
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="keywords" content="Alan Koda, Film Post, Audio Post, Sound Post, Freelance Audio, Freelance Sound, Freelance Post Production, Effects Editor, Sound Design, Sound Designer, Sound Design Austin, Austin Post Production, Game Audio, Film Sound Design, Film Audio, Film Sound, Game Sound Design, Post Production Audio, Post Production Sound, Film Post Production" /> 
  <meta name="description" content="Professional website for Alan Koda - Sound Design for Film, Television, and Games" />
  <link rel="shortcut icon" href="assets/images/AlanKoda_Favicon.ico" />
  <link rel="apple-touch-icon" media="screen and (resolution: 163dpi)" href="/link/to/iOS-57px.png" />
  <link rel="apple-touch-icon" media="screen and (resolution: 132dpi)" href="/link/to/iOS-72px.png" />
  <link rel="apple-touch-icon" media="screen and (resolution: 326dpi)" href="/link/to/iOS-114px.png" />

  <title>Alan Koda • Audio &amp; Design for Media</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <!-- <%= javascript_include_tag "application", "data-turbolinks-track" => true %> -->
  <%= csrf_meta_tags %>

  <script src="http://widgets.twimg.com/j/2/widget.js"></script>

	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-24890951-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>


			<script type="text/javascript">
				$(document).ready(function() {

				/* This is basic - uses default settings */

				$("a.lightbox").fancybox();

				});

			});
			</script>




</head>

app/views/layouts/_header.html.erb
<div id="top">
	<div id="banner">

		<%= link_to (image_tag("AlanKoda_BlackBadge120x120.png", alt: "Alan Koda Banner", id: "bannerimage")), root_path %>

		<div id="bannertext">

			<p id="maintitle">Alan Koda</p>

			<ul id="contactinfo">
				<li><em>Audio &amp; Design for Media</em></li>
				<li>mail: <%= link_to "alan@alankoda.com", "mailto:alan@alankoda.com" %></li>
				<li>phone: <%= link_to "817.308.5446", "tel:+18173085446" %></li>
			</ul>
		</div>
	</div>

	<nav class="mainnav" id="topnav">
		<ul>
			<li class="about">About
				<nav class="subnav" id="aboutsubnav">
					<ul>
						<li class="aboutme"><%= link_to "About Me", aboutme_path %></li>
						<li class="resume"><%= link_to "Resume", resume_path %></li>
						<li class="awards"><%= link_to "Awards", awards_path %></li>
					</ul>
				</nav>
			</li>
			<li class="work"><%= link_to "Work", works_path %>
				<nav class="subnav" id="worksubnav">
					<ul>
						<li class="films"><%= link_to "Sound", sound_path %></li>
						<li class="design"><%= link_to "Design", design_path %></li>
						<li class="software"><%= link_to "Software", software_path %></li>
					</ul>
				</nav>
			</li>
			<li class="contact">Contact
				<nav class="subnav" id="contactsubnav">
					<ul>
						<li><%= link_to "alan@alankoda.com", "mailto:alan@alankoda.com" %></li>
						<li><%= link_to "817.308.5446", "tel:+18173085446" %></li>
					</ul>
				</nav>
			</li>
		</ul>
	</nav>

	<p id="sociallinks">
		<%= link_to image_tag("twitter_icon_bw.jpg", alt: "twitter_icon_color", mouseover: "twitter_icon_color.jpg"), "http://www.twitter.com/KodaSound/" %>
		<%= link_to image_tag("tumblr_icon_bw.jpg", alt: "tumblr_icon_color", mouseover: "tumblr_icon_color.jpg"), "http://kodasound.tumblr.com/" %>
		<%= link_to image_tag("linkedin_icon_bw.jpg", alt: "linkedin_icon_color", mouseover: "linkedin_icon_color.jpg"), "http://www.linkedin.com/in/alankoda/" %>
		<%= link_to image_tag("facebook_icon_bw.jpg", alt: "facebook_icon_color", mouseover: "facebook_icon_color.jpg"), "http://www.facebook.com/pages/KodaSound/133981336687315/" %>
	</p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<%= render "layouts/head" %>
<body>
	<div id="gutters">
		<div id="container">
			<div id="content">
				
				<%= render "layouts/header" %>

				<div id="subcontents">

					<%= yield %>

				</div>
				
				<%= render "layouts/footer" %>

			</div>
		</div>
	</div>
</body>
</html>

app/views/static_pages/about.html.erb
<div class="section" id="about">
	<p><%= @work %></p>
	
	<%= yield %>

</div>

app/views/static_pages/about/awards.html.erb
<div class="subsection" id="awards">

	<h2>Awards and Recognition</h2>
	
	<h3>Nominee for <em>Verna Fields Award in Sound Editing for Student Filmmakers</em> for Secret Number (student film)</h3>
	<p>Golden Reel Awards, Motion Picture Sound Editors, 2012</p>
	
	<h3>Nominee for <em>Verna Fields Award in Sound Editing for Student Filmmakers</em> for En Route (student film)</h3>
	<p>Golden Reel Awards, Motion Picture Sound Editors, 2011</p>

	<h3>Nominee for <em>Student Academy Award</em> for The Girl and the Fox (student film)</h3>
	<p>Academy of Motion Picture Arts and Sciences, 2011</p>

	<h3><em>Outstanding Achievement Award</em></h3>
	<p>Sound Design department, Savannah College of Art and Design, 2011</p>
	
	<h3><em>Artistic Achievement Award for an Outstanding Body of Work</em></h3>
	<p>SCADemy Awards, Savannah College of Art and Design, 2010</p>

	<h3>Nominee <em>for Best Sound</em> for Atrophy (student film)</h3>
	<p>SCADemy Awards, Savannah College of Art and Design, 2010</p>
	
	<h3>Nominee for <em>Best Sound</em> for En Route (student film)</h3>
	<p>SCADemy Awards, Savannah College of Art and Design, 2010</p>
	
	<h3><em>1st Place, Sound Art Category for</em> Videodrums (interactive work)</h3>
	<p>CoMotion Student Contest, Savannah College of Art and Design, 2010</p>
	
</div>

app/views/static_pages/about/me.html.erb
<div class="subsection" id="aboutme">

	<h2>About Me</h2>
	<h5>I am an audio designer for film, television, and games.</h5>
	
	<p>I hold an <em>MFA in Sound Design</em> from the Savannah College of Art and Design.  My work there centered on audio for short films, animation, and sound art.  However, <em>I have a longstanding passion for video games</em>, and so I hope to find my way into that neck of the audio woods as well.</p>
	
	<p><em>My thesis work at SCAD focused on redesigning Digital Audio Workstation interfaces for post-production</em>, and how to effectively develop interaction with audio software beyond analog hardware emulation. Based on research, interviews, etc., I made several prototype designs for touch-based audio software, utilizing novel interaction paradigms.  I will continue developing my design into a functional prototype, and hopefully delve deeper into designing products for creative media-making people.</p>
	
	<h5><a title="Cutting the Cables, by Alan Koda" href="http://www.alankoda.com/download.php?file=Koda_CuttingtheCables.pdf" onClick="_gaq.push(['_trackEvent', 'Documents', 'Download', 'Thesis']);">&rarr; Download a copy of my thesis</a></h5>

</div>

app/views/static_pages/about/resume.html.erb
<div class="subsection" id="resume">
	
	<h2>Résumé</h2>
	<p id="download"><a href="http://www.alankoda.com/download.php?file=AlanKoda_resume2012_fullgeneral.pdf" onClick="_gaq.push(['_trackEvent', 'Documents', 'Download', 'Resume']);">download pdf</a></p>
	
	<h5>Summary of Skills</h5>
		<ul>
			<li>Postproduction sound effects, foley, dialog/ADR/dubbing, mix, and sound team supervision for film, television, and games</li>
			<li>Composition, editing, and mixing for music (including music for picture)</li>
			<li>Implementation of audio, video and audio/visual control methods in Max/MSP/Jitter</li>
			<li>Pro Tools 8 certified Post Operator</li>
			<li>Visual design, graphic design, digital illustration</li>
			<li>Web design, user interaction and interface design</li>
		</ul>
		
		
	<h5>Experience</h5>
		<h3>Freelance Sound and Graphic Design</h3>
			<h4><em>(2011 &mdash; current)</em></h4>
				<ul>
					<li>Recorded production sound, designed sound assets, and mixed final soundtracks</li>
					<li>Designed posters, flyers, logos, and icons</li>
				</ul>
		<h3>Sound Recordist/Designer/Composer</h3>
			<h4>Blue Goggles Films <em>(2011 &mdash; current)</em></h4>
				<ul>
					<li>Co-owned production and postproduction sound duties for short video and webisode productions</li>
					<li>Composed original music and score</li>
				</ul>
		<h3>Virtual Assistant</h3>
			<h4>Om Freely <em>(2011 &mdash; 2012)</em></h4>
				<ul>
					<li>Managed audio assets, including editing and exporting to appropriate formats</li>
					<li>Maintained daily front-end web presence; updated daily page content and media assets</li>
				</ul>
		<h3>Web Designer</h3>
			<h4>Brown &amp; Koda Web <em>(2011 &mdash; current)</em></h4>
				<ul>
					<li>Conceptualized and designed site and page layouts; crafted brand logos and identities; generated site assets for web integration</li>
				</ul>
		<h3>Animator</h3>
			<h4>Allure Energy, Incorporated <em>(2011 &mdash; 2012)</em></h4>
				<ul>
					<li>Wrote, animated, narrated, and scored six ‘Energy Saving Tips’ videos for use with smart thermostat product</li>
				</ul>
		<h3>Team Lead, 3M-Sponsored Design Project</h3>
			<h4>Savannah College of Art and Design <em>(2011)</em></h4>
				<ul>
					<li>Led a design team to develop new concepts for touch interaction, utilizing 3M’s emerging multitouch technologies</li>
					<li>Developed collaborative multitouch picture editing concept for large multitouch hardware</li>
					<li>Illustrated concepts via mockups, scenario enaction, and demonstration videos</li>
				</ul>
		<h3>Master’s Thesis &mdash; <em>Cutting the Cables:  Developing DAWs Beyond Analog Methods</em></h3>
			<h4>Savannah College of Art and Design <em>(2011)</em></h4>
				<ul>
					<li>Analyzed past and current postproduction sound methods and workflows to pinpoint user experience issues</li>
					<li>Developed several prototypes for a novel alternative touch interaction DAW system</li>
				</ul>

			
	<h5>Notable Activities</h5>
		<h3>Quality Assurance &amp; Engineering Intern</h3>
		<h4>The Kitchen, dubbing and subtitling services <em>(September &mdash; November 2010)</em></h4>
			<ul>
				<li>Converted casting sheets into online digital cast database, allowing for quick assessment of casting needs and recording progress per episode</li>
				<li>Crafted guide for The Kitchen’s engineering process, including use of proprietary dubbing software and talent billing, for use by future interns</li>
			</ul>
		<h3>Treasurer, Professional Audio Student Organization (PASO)</h3>
		<h4>Savannah College of Art and Design <em>(2009 &mdash; 2010)</em></h4>
			<ul>
				<li>Doubled allocated funds between September and February, winning the club’s largest grant for a single proposal.</li>
				<li>Coordinated travel, accommodation, and venue arrangements for four guest lecturers – Martin Atkins, Jeff Wexler, Ed Greene, and Alexander Brandon – as well as creating all promotional material and coordinating marketing.</li>
				<li>Coordinated two-day interdepartmental event CoMotion with Motion Media club.</li>
			</ul>
		<h3>Sound Design and Math Tutor</h3>
		<h4>Savannah College of Art and Design <em>(2009 &mdash; 2010)</em></h4>
			<ul>
				<li>Tutored students in Pro Tools, production and postproduction workflow, Max/MSP/Jitter, and college algebra and geometry</li>
			</ul>
		<h3>Interactive Max/MSP Projects &mdash; various personal projects</h3>
		<h4><em>(2009 &mdash; current)</em></h4>
			<ul>
				<li>Designed interactive audiovisual systems (audio processors, audio/video sequencers, etc.); created UI for various input (keyboard, mouse, video tracking, MIDI via wifi) for live interaction</li>
			</ul>

			
			
	<h5>Awards and Honors</h5>
		<ul>
			<li>Nominee for 2012 <em>Verna Fields Award (for Secret Number)</em>, awarded by the Motion Picture Sound Editors (MPSE) for excellence in student film sound editing</li>
			<li>Nominee for 2011 <em>Verna Fields Award (for En Route)</em>, awarded by the Motion Picture Sound Editors (MPSE) for excellence in student film sound editing</li>
			<li>Recipient of <em>Artistic Achievement Award for an Outstanding Body of Work</em>, for special recognition by SCAD film department faculty at 2010 SCADemy Awards</li>
			<li>Recipient of <em>Outstanding Achievement Award</em> at 2011 SCAD Commencement</li>
			<li>First Place winner in Sound Art for ‘Videodrums’ audiovisual concept, at 2011 CoMotion Contest</li>
		</ul>
		
		
	<h5>Education</h5>
		<h3>Master of Fine Arts (MFA) in Sound Design</h4>
		<h4><em>3.9 GPA,</em> Savannah College of Art and Design, Savannah, Georgia (2011)</h3>
		
		<h3>Bachelor of Arts (BA) in Radio/Television/Film</h3>
		<h4><em>magna cum laude, 3.9 GPA,</em> University of North Texas, Denton, Texas (2007)</h4>

</div>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/index.html.erb
<div class="section" id="home">

	<div id="welcome">
	
	<iframe onClick="_gaq.push(['_trackEvent', 'Videos', 'Play', 'Demo Reel']);" src="http://player.vimeo.com/hubnut/album/2195518?color=44bbff&amp;background=000000&amp;slideshow=0&amp;video_title=1&amp;video_byline=1" webkitAllowFullScreen mozallowfullscreen allowFullScreen width="560" height="315" frameborder="0"></iframe>
	
	<h1>Welcome to my website.</h1>
	<h1>I make sounds for pictures and games and art.</h1>
	<h1>And I design.</h1>
	
	</div>
	
	
	<p>Glad to see you here.  I do sound.  Whether it's effects, design, composition, narration, or even location sound, I make sure that my <%= link_to "audio work", sound_path %> meets the vision of my clients.</p>
	
	<p>I'm also a visual, interaction, and experience designer, and I <%= link_to "make web sites", design_path %>, <%= link_to "code Max/MSP patches", software_path %>, and <a title="Cutting the Cables, by Alan Koda" href="http://www.alankoda.com/download.php?file=Koda_CuttingtheCables.pdf" onClick="_gaq.push(['_trackEvent', 'Documents', 'Download', 'Thesis']);">try to make software better.</a></p>
	
	<p>When I'm not knee-deep in Pro Tools or Coda, I <%= link_to "doodle in Illustrator", design_path %>, follow <%= link_to "indie games", "http://venuspatrol.com/" %>, and play whatever instrument happens to be in front of me.</p>
	
	<h5><a title="Alan Koda Design Portfolio" href="http://www.alankoda.com/download.php?file=AlanKoda_DesignPortfolio2013.pdf" onClick="_gaq.push(['_trackEvent', 'Documents', 'Download', 'Portfolio']);">&rarr; Download my Visual Design Portfolio</a></h5>
	
	<p>
		<h2>The Blog</h2>
		<aside>powered by <%= link_to "Tumblr", "http://www.tumblr.com" %></aside>
		<script type="text/javascript" src="http://kodasound.tumblr.com/js"></script>
		<p><%= link_to "Visit my Tumblr for more posts &rarr;".html_safe, "http://kodasound.tumblr.com/page/2" %></p>
	</p>
	
	<p class="backtotop"><a href="#">&uarr; back to top</a></p>
	
</div>

app/views/static_pages/portfolio/design.html.erb
<div class="section" id="work">
	<div class="subsection" id="design">

	<h2>Design</h2>

	<h5><a title="Alan Koda Design Portfolio" href="http://www.alankoda.com/download.php?file=AlanKoda_DesignPortfolio2013.pdf" onClick="_gaq.push(['_trackEvent', 'Documents', 'Download', 'Portfolio']);">&rarr; Download my Visual Design Portfolio</a></h5>

	<h4>Filter by category:</h4>
		<nav class="filternav">
			<ul>
				<li class="interaction">Interaction</li>
				<li class="animation">Animation</li>
				<li class="logos">Logos</li>
				<li class="flyers">Promotional</li>
				<li class="webdesign">Web Design</li>
				<li class="personalprojects">Other Projects</li>
				<li class="all">view all</li>
			</ul>
		</nav>

		<% @works.each do |work| %>
			<% if work.av == "design" %>
				<%= render partial: "works/work_entry", locals: { work: work }%>
			<% end %>
	    <% end %>
	
		<p class="backtotop designbacktotop"><a href="#">&uarr; back to top</a></p>
	</div>	
</div>

app/views/static_pages/portfolio/software.html.erb
<div class="section" id="work">
	<div class="subsection" id="software">

		<h2>Software</h2>
	
		<p><a title="Cycling '74" href="http://www.cycling74.com/">Max/MSP</a> is a visual programming language.  It's like code, but with objects and patch cables and sliders where brackets and semicolons usually are.  I've used Max/MSP for the past three years to develop concepts to bridge the gap between audio and video.  Check back for updates soon.</p>
	
		<h3><em>Motion Music</em> (in conjunction with Stephen Fortunato)</h3>
		<h4>Motion-based Mixing</h4>
		<h4><a title="Sound Art Showcase 2011: Stephen Fortunato" href="http://facultypages.scad.edu/~aruschko/SoundArtWebsite/Stephen%20Fortunato.html/">SCAD Sound Art Showcase 2011</a></h4>
		<p>Uses motion detection to dynamically mix tracks in an audio file; more motion causes more tracks to sound.</p>

		<h3><em>Ambience</em></h3>
		<h4>Reactive Audiovisual Stimulus</h4>
		<%= image_tag("Ambience1_500.png", alt: "Ambience Screenshot") %>
		<p>A field of color squares and a set of oscillators are driven by a semi-random algorithm.  Both visual and aural stimulus are dynamically altered via detection of motion, ambient light, and color.  The squares more or less reflect the averaged color of the camera's input.  Intended as a sort of reactive wall art.</p>
		<h4><a title="Ambience download" href="http://www.alankoda.com/AlanKoda_ambience.zip" onClick="_gaq.push(['_trackEvent', 'Apps', 'Download', 'Ambience']);">Download 'Ambience' (standalone Mac app)</a></h4>

		<h3><em>Video Organ</em> (in conjunction with Stephen Fortunato)</h3>

		<h3><em>SeeqTrem</em></h3>
		<h4>Multistage Amplitude Manipulation</h4>
		<%= image_tag("SeeqTrem2_500.png", alt: "SeeqTrem Screenshot") %>
		<p>Inspired by the ZVex SeekTrem &mdash; using either a file or microphone input, generates custom tremolo effects, stepping sequentially through 2 to 8 level controls.</p>
		<h4><a title="SeeqTrem download" href="http://www.alankoda.com/AlanKoda_seeqtrem.zip" onClick="_gaq.push(['_trackEvent', 'Apps', 'Download', 'SeeqTrem']);">Download 'SeeqTrem' (standalone Mac app)</a></h4>

		<h3><em>VideoDrums</em></h3>
		<h4>Musical Video Sequencing</h4>
		<h4><a title="Sound Art Showcase 2010: Alan Koda" href="http://facultypages.scad.edu/~aruschko/SoundArtWebsite/Alan%20Koda.html/">SCAD Sound Art Showcase 2010</a></h4>
		<%= image_tag("Videodrums1_500.png", alt: "Videodrums Screenshot 1") %>
		<%= image_tag("Videodrums2_500.png", alt: "Videodrums Screenshot 2") %>
		<p>Uses an 808-style step sequencer to drive the playhead of a video; the video (and its audio) is 'played' like a sequenced instrument.  Keyboard shortcuts allow the user multiple options during play for DJ-style live manipulation.  Markers can also be placed on the fly for instant recall of any point in the video.</p>
			<ul><li>Won 1st Place for Sound Art, 2010 CoMotion Contest</li></ul>
		<h4><a title="VideoDrums download" href="http://www.alankoda.com/AlanKoda_videodrums.zip" onClick="_gaq.push(['_trackEvent', 'Apps', 'Download', 'VideoDrums']);">Download 'VideoDrums' (standalone Mac app)</a></h4>
	</div>
</div>

app/views/static_pages/portfolio/sound.html.erb
<div class="section" id="work">
	<div class="subsection" id="films">

		<h2>Sound</h2>		
	
		<h4>Filter by category:</h4>
	
		<nav class="filternav">
			<ul>
				<li class="production">Production</li>
				<li class="post">Postproduction</li>
				<li class="composition">Composition</li>
				<li class="withvideo">With video</li>
				<br />
				<li class="withawards">With awards</li>
				<li class="depixelated">De-pixelated</li>
				<li class="bitparts">BIT Parts</li>
				<li class="all">view all</li>
			</ul>
		</nav>
	
		<% @works.each do |work| %>
			<% if work.av == "sound" %>
				<%= render partial: "works/work_entry", locals: { work: work }%>
			<% end %>
	    <% end %>
	
		<p class="backtotop designbacktotop"><a href="#">&uarr; back to top</a></p>

	</div>
</div>

app/views/works/_work_entry_edit.erb
<p>
	<%= link_to 'Show', work %>
    <%= link_to 'Edit', edit_work_path(work) %>
    <%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/works/edit.html.erb
<h2>Editing work</h2>

<%= render 'form' %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
<h2>Listing all work</h2>

<h1>Sound</h1>  
<ul>
    <% @works.each do |work| %>
		<% if work.av == "sound" %>
			<%= render partial: "work_entry", locals: { work: work }%>
			<%= render partial: "work_entry_edit", locals: { work: work }%>
		<% end %>
    <% end %>
</ul>

<h1>Design</h1>
<ul>
    <% @works.each do |work| %>
		<% if work.av == "design" %>
			<%= render partial: "work_entry", locals: { work: work }%>
			<%= render partial: "work_entry_edit", locals: { work: work }%>
		<% end %>
    <% end %>
</ul>

<br>

<%= link_to 'New Work', new_work_path %>

app/views/works/new.html.erb
<h1>New work</h1>

<%= render 'form' %>

<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<%= content_tag :div, class: @work.category do %>
	<%= content_tag :h3, @work.name %>
	<%= content_tag :h4, @work.series if @work.series %>
  	<%= content_tag :h4, @work.publisher if @work.publisher %>
	<%= @work.role %>
	<%= @work.embed.html_safe %>

	<%= link_to 'Edit', edit_work_path(@work) %> |
	<%= link_to 'Back', works_path %>
<% end %>